apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        env: prod
        app: gateway-app
        app.kubernetes.io/name: gateway-app
    spec:
      containers:
      - name: gateway-app
        image: dumindapium/gateway:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: http://+:5000
---

apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app.kubernetes.io/name: gateway-app
  ports:
  - name: sales-app-port
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-app
  template:
    metadata:
      labels:
        env: prod
        app: orders-app
        app.kubernetes.io/name: orders-app
    spec:
      containers:
      - name: orders-app
        image: dumindapium/orderservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5100
        env:
        - name: ASPNETCORE_URLS
          value: http://+:5100
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: orders-app
  ports:
    - protocol: TCP
      port: 5100
      targetPort: 5100
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-app
  template:
    metadata:
      labels:
        env: prod
        app: catalog-app
        app.kubernetes.io/name: catalog-app
    spec:
      containers:
      - name: catalog-app
        image: dumindapium/catalogservice:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5200
        env:
        - name: ASPNETCORE_URLS
          value: http://+:5200
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-app
  ports:
    - protocol: TCP
      port: 5200
      targetPort: 5200
  type: ClusterIP
