apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  labels:
    name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-volume-claim
  containers:
  - name: pv-pod-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    name: pv-pod
  ports:
  - name: sales-app-port
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer